In [15]:
import pandas as pd
df=pd.read_csv("Orders_data.csv")
df.head(2)

,Row ID,Order ID,Order Date,Year,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Sales Amount,Quantity,Discount,Profit,SalesPerson
0,1,CA-2016-152156,08-11-2020,2020,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,261.96,2,0.0,41.9136,SP_202
1,2,CA-2016-152156,08-11-2020,2020,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,731.94,3,0.0,219.5820,SP_430

In [36]:
#df.query('City == "Henderson" and Year == 2021')
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Year', 'Ship Mode', 'Customer ID',
       'Segment', 'Country', 'City', 'State', 'Postal Code', 'Region',
       'Product ID', 'Sales Amount', 'Quantity', 'Discount', 'Profit',
       'SalesPerson'],
      dtype='object')

In [42]:
df["Ship Mode"].memory_usage(deep =True)

10539

In [41]:
df["Ship Mode"] = df["Ship Mode"].astype("category")

In [45]:
df1= pd.DataFrame({
    "Name": ["A", "B", "C"],
    "Colors": [["Red", "Yellow"], ["Blue"], ["Green", "Purple", "Black"]]
    })
df1

  Name                  Colors
0    A           [Red, Yellow]
1    B                  [Blue]
2    C  [Green, Purple, Black]

In [46]:
df1.explode("Colors")

  Name  Colors
0    A     Red
0    A  Yellow
1    B    Blue
2    C   Green
2    C  Purple
2    C   Black

In [51]:
df1["Colors"].str.split(",")

0    NaN
1    NaN
2    NaN
Name: Colors, dtype: object

In [54]:
df1["Colors"].apply(
    lambda x: x if isinstance(x, list) or pd.isna(x) else x.split(", "))

0             [Red, Yellow]
1                    [Blue]
2    [Green, Purple, Black]
Name: Colors, dtype: object

0             Henderson
1             Henderson
2           Los Angeles
3       Fort Lauderdale
4       Fort Lauderdale
             ...
9989              Miami
9990         Costa Mesa
9991         Costa Mesa
9992         Costa Mesa
9993        Westminster
Name: City, Length: 9994, dtype: category
Categories (531, object): ['Aberdeen', 'Abilene', 'Akron', 'Albuquerque', ..., 'Yonkers', 'York', 'Yucaipa', 'Yuma']

In [58]:
df.head(4)

,Row ID,Order ID,Order Date,Year,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Sales Amount,Quantity,Discount,Profit,SalesPerson
0,1,CA-2016-152156,08-11-2020,2020,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,261.9600,2,0.00,41.9136,SP_202
1,2,CA-2016-152156,08-11-2020,2020,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,731.9400,3,0.00,219.5820,SP_430
2,3,CA-2016-138688,12-06-2020,2020,Second Class,DV-13045,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,14.6200,2,0.00,6.8714,SP_344
3,4,US-2015-108966,11-10-2019,2019,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,33311,South,FUR-TA-10000577,957.5775,5,0.45,-383.0310,SP_388

In [80]:
df[0:3]

,Row ID,Order ID,Order Date,Year,Ship Mode,Customer ID,Segment,Country,City,State,Postal Code,Region,Product ID,Sales Amount,Quantity,Discount,Profit,SalesPerson
0,1,CA-2016-152156,08-11-2020,2020,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-BO-10001798,261.96,2,0.0,41.9136,SP_202
1,2,CA-2016-152156,08-11-2020,2020,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,42420,South,FUR-CH-10000454,731.94,3,0.0,219.5820,SP_430
2,3,CA-2016-138688,12-06-2020,2020,Second Class,DV-13045,Corporate,United States,Los Angeles,California,90036,West,OFF-LA-10000240,14.62,2,0.0,6.8714,SP_344

In [85]:
df.iloc[[1,4,5],[9]]

        State
1    Kentucky
4     Florida
5  California

In [17]:
d = [1,3,5,9,6]
c = [2,4,8,7]
i = 0
j = 0
arr = []
n = 0
while i < len(d):
    while j < len(c):
        if d[i] < d[j]:
            arr[n] = d[i]
            i += 1
            print(arr)
        else:
            arr[n] = c[j]
            j += 1
    n+= 1
arr

IndexError: list assignment index out of range