In [ ]:
n = 2050
N = str(n)
s = ""
u = 0
for i in range(len(N)):
    u = n%10
    if u > 0:
        pass 
        if u == 0:
            n = n//10
            continue
    s = s+ str(u)
    n = n//10
int(s)

52

In [ ]:
words = ["apple", "mango", "icecream", "potato"]
for i in words:
    count[i] = count.get()

NameError: name 'count' is not defined

In [6]:
for i in words:
    print(i)

apple
mango
icecream
potato

In [ ]:
a = {i:i**2 for i in range(5)}
a.get()

:

In [40]:
s= str(0)
s

'0'

In [9]:
"a"+"a"

'aa'

In [26]:
n//10

0

In [ ]:
"".join(["1","2","3","4] if )

SyntaxError: closing parenthesis ')' does not match opening parenthesis '[' (3007656758.py, line 1)

In [44]:
[i for i in str(1234)]

['1', '2', '3', '4']

In [45]:
n = 2010
"".join([d for d in str(n) if d != "0"])

'21'

In [88]:
n = 11
i = 2
while i <n:
    if n%i != 0 or n ==i:
        print(True)
    else:
        print(False)
    i = i+1

True
True
True
True
True
True
True
True
True

In [ ]:
  for i in range(1, n+1):
            if i%i == 0:
                return True
        return False

In [ ]:
g = range(1,10)

In [89]:
for i in g:
    print(i)

1
2
3
4
5
6
7
8
9

In [100]:
##DSA

In [128]:
arr = [16, 17, 4, 3, 5, 2]
s = 0
n = len(arr)
d = []
for i in range(n):
    for j in range(i+1,n):
        if arr[i]< arr[j]:
            break
    else:
        d.append(arr[i])       
print(d)

[17, 5, 2]

In [ ]:
arr = [16, 17, 4, 3, 5, 2]
arr[-5:1:-1]

[2, 5, 3, 4]

In [143]:
arr = [61,61,17]
n = len(arr)
arr_max = arr[-1]
df = []
df.append(arr_max)
for i in range(n-2,-1,-1):
    if arr[i]>=arr_max:
        arr_max = arr[i]
        df.append(arr_max)
df.reverse()
df

[61, 61, 17]

In [198]:
arr= [77,7,5,6,55,6,6,5]
g = set()
gg = []
idx = 0
for i in range(len(arr)):
    if arr[i]not in g:
        g.add(arr[i])
        arr[idx] = arr[i]
        idx = idx +1
for i in range(idx):
    print(arr[i], end = " ")

77 7 5 6 55

In [185]:
def removeDuplicates(arr):
    
    seen = set()

    idx = 0

    for i in range(len(arr)):
        if arr[i] not in seen:
            seen.add(arr[i])
            arr[idx] = arr[i]
            idx += 1
    return idx

In [195]:
arr1=[10,9,8 ,9 ,8]
a = removeDuplicates(arr1)
for i in range(a):
    print(arr1[i], end = " ")

10 9 8

In [213]:
n = 1004
s = str(n)
s =s.replace("0","5")
int(s)

1554

In [207]:
s.replace("0","5")

'1554'

In [215]:
n = 20
l = []
import math
for i in range(1,int(math.sqrt(n))+1):
    if n%i ==0:
        l.append(i)
        if i != n // i:   # avoid duplicate
            l.append(n // i)
l

[1, 20, 2, 10, 4, 5]

In [216]:
## ADD TWO FRACTIONS

In [219]:
A = 1
B = 67
E =8
F =56

C = A/B + E/F
C

0.1577825159914712

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("Salaries.csv", low_memory = False)

In [247]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148654 non-null  int64
 1   EmployeeName      148654 non-null  object
 2   JobTitle          148654 non-null  object
 3   BasePay           148049 non-null  object
 4   OvertimePay       148654 non-null  object
 5   OtherPay          148654 non-null  object
 6   Benefits          112495 non-null  object
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(3), int64(2), object(8)
memory usage: 14.7+ MB

In [301]:
df["BasePay"].isna().nunique()

2

In [278]:
df["BasePay"].isna().unique()

array([False,  True])

In [298]:
df["BasePay"] = pd.to_numeric(df["BasePay"], errors="coerce")

In [299]:
df["BasePay"][pd.to_numeric(df["BasePay"]).isna()].unique()

array([nan])

In [305]:
df["BasePay"][df["BasePay"].apply(lambda x: not str(x).replace('.','').isnumeric())].unique()

array([-166.01, -121.63, -109.22, -106.6 , -101.88,  -93.14,  -87.38,
        -75.67,  -59.59,  -30.58,   -9.5 ,     nan])

In [307]:
df["BasePay"][pd.to_numeric(df["BasePay"], errors="coerce").isna()].unique()

array([nan])

In [314]:
df["BasePay"].apply(lambda x: x is np.nan)

0         False
1         False
2         False
3         False
4         False
          ...
148649    False
148650    False
148651    False
148652    False
148653    False
Name: BasePay, Length: 148654, dtype: bool

In [323]:
import math
df["BasePay"][df["BasePay"].apply(lambda x: math.isnan(x) if isinstance(x, float) else False)].nunique(dropna = False)

1

In [332]:
df.head(2)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN

In [331]:
df["BasePay"].mean()

np.float64(66325.44884048769)

In [338]:
df["OvertimePay"] = pd.to_numeric(df["OvertimePay"], errors = "coerce")

In [344]:
df["OvertimePay"].max()

np.float64(245131.88)

In [347]:
df[df["EmployeeName"] == "JOSEPH DRISCOLL"]["JobTitle"]

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [348]:
df[df["EmployeeName"] == "JOSEPH DRISCOLL"]["TotalPayBenefits"]

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [380]:
df[df["TotalPayBenefits"] ==df["TotalPayBenefits"].max()]["EmployeeName"]

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [96]:
df.head(2)

   Id    EmployeeName  ...         Agency  Status
0   1  NATHANIEL FORD  ...  San Francisco     NaN
1   2    GARY JIMENEZ  ...  San Francisco     NaN

[2 rows x 13 columns]

In [466]:
df.groupby("Year").mean(numeric_only = True)["BasePay"]

Year
2011    63595.956517
2012    65436.406857
2013    69630.030216
2014    66564.421924
Name: BasePay, dtype: float64

In [404]:
df.loc[df["TotalPayBenefits"].idxmin(),["EmployeeName","TotalPayBenefits"]]

EmployeeName        Joe Lopez
TotalPayBenefits      -618.13
Name: 148653, dtype: object

In [411]:
df.loc[df["TotalPayBenefits"].argmin(),["EmployeeName","TotalPayBenefits"]]

EmployeeName        Joe Lopez
TotalPayBenefits      -618.13
Name: 148653, dtype: object

In [429]:
df.iloc[0, 6]

nan

In [426]:
(df["BasePay"]>100000).to_numpy()

array([ True,  True,  True, ..., False, False, False], shape=(148654,))

In [442]:
df.iloc[df["TotalPayBenefits"].argmin()]["EmployeeName"]

'Joe Lopez'

In [ ]:
df.iloc[-1]

Id                                      148654
EmployeeName                         Joe Lopez
JobTitle            Counselor, Log Cabin Ranch
BasePay                                    0.0
OvertimePay                                0.0
OtherPay                               -618.13
Benefits                                  0.00
TotalPay                               -618.13
TotalPayBenefits                       -618.13
Year                                      2014
Notes                                      NaN
Agency                           San Francisco
Status                                      PT
Name: 148653, dtype: object

In [469]:
df["JobTitle"].nunique()

2159

In [ ]:
df["JobTitle"].value_counts(ascending=False).head(5)

JobTitle
Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: count, dtype: int64

In [74]:
df[df["Year"]==2013]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
72925,72926,Gregory P Suhr,Chief of Police,319275.01,0.0,20007.06,86533.21,339282.07,425815.28,2013,NaN,San Francisco,NaN
72926,72927,Joanne M Hayes-White,"Chief, Fire Department",313686.01,0.0,23236.0,85431.39,336922.01,422353.40,2013,NaN,San Francisco,NaN
72927,72928,Samson Lai,"Battalion Chief, Fire Suppress",186236.42,131217.63,29648.27,57064.95,347102.32,404167.27,2013,NaN,San Francisco,NaN
72928,72929,Ellen G Moffatt,Asst Med Examiner,272855.51,23727.91,38954.54,66198.92,335537.96,401736.88,2013,NaN,San Francisco,NaN
72929,72930,Robert L Shaw,"Dep Dir for Investments, Ret",315572.01,0.0,0.0,82849.66,315572.01,398421.67,2013,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
110526,110527,Arthur L Curry,PS Aide Health Services,NaN,0.0,10.67,0.0,10.67,10.67,2013,NaN,San Francisco,NaN
110527,110528,Nereida Vega,Senior Clerk,NaN,0.0,5.56,0.0,5.56,5.56,2013,NaN,San Francisco,NaN
110528,110529,Timothy E Gibson,Police Officer 3,NaN,0.0,0.0,-2.73,0.00,-2.73,2013,NaN,San Francisco,NaN
110529,110530,Mark E Laherty,Police Officer 3,NaN,0.0,0.0,-8.2,0.00,-8.20,2013,NaN,San Francisco,NaN
110530,110531,David P Kucia,Police Officer 3,NaN,0.0,0.0,-33.89,0.00,-33.89,2013,NaN,San Francisco,NaN

In [83]:
df["BasePay"] = pd.to_numeric(df["BasePay"], errors ="coerce")

In [84]:
df.query("Year==2013 and BasePay > 100000")

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
72925,72926,Gregory P Suhr,Chief of Police,319275.01,0.0,20007.06,86533.21,339282.07,425815.28,2013,NaN,San Francisco,NaN
72926,72927,Joanne M Hayes-White,"Chief, Fire Department",313686.01,0.0,23236.0,85431.39,336922.01,422353.40,2013,NaN,San Francisco,NaN
72927,72928,Samson Lai,"Battalion Chief, Fire Suppress",186236.42,131217.63,29648.27,57064.95,347102.32,404167.27,2013,NaN,San Francisco,NaN
72928,72929,Ellen G Moffatt,Asst Med Examiner,272855.51,23727.91,38954.54,66198.92,335537.96,401736.88,2013,NaN,San Francisco,NaN
72929,72930,Robert L Shaw,"Dep Dir for Investments, Ret",315572.01,0.0,0.0,82849.66,315572.01,398421.67,2013,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
90326,90327,Dana M Freiser,Special Nurse,100478.65,1751.86,3364.19,1055.94,105594.70,106650.64,2013,NaN,San Francisco,NaN
90342,90343,Dawn Blaney,Special Nurse,103843.02,791.13,1946.62,0.0,106580.77,106580.77,2013,NaN,San Francisco,NaN
90478,90479,Julia Dyett,Special Nurse,101451.76,1442.67,3350.16,0.0,106244.59,106244.59,2013,NaN,San Francisco,NaN
90726,90727,Chinelo V Amah,Special Nurse,101069.34,0.0,3293.37,1043.68,104362.71,105406.39,2013,NaN,San Francisco,NaN
90832,90833,Stephanie Reidy,Special Nurse,103989.30,0.0,0.0,1039.87,103989.30,105029.17,2013,NaN,San Francisco,NaN

In [49]:
sum(df[df["Year"]==2013]["JobTitle"].value_counts()==1)

202

In [72]:
df["JobTitle"].str.split()

0         [GENERAL, MANAGER-METROPOLITAN, TRANSIT, AUTHO...
1                      [CAPTAIN, III, (POLICE, DEPARTMENT)]
2                      [CAPTAIN, III, (POLICE, DEPARTMENT)]
3                [WIRE, ROPE, CABLE, MAINTENANCE, MECHANIC]
4         [DEPUTY, CHIEF, OF, DEPARTMENT,(FIRE, DEPARTME...
                                ...
148649                                          [Custodian]
148650                                      [Not, provided]
148651                                      [Not, provided]
148652                                      [Not, provided]
148653                      [Counselor,, Log, Cabin, Ranch]
Name: JobTitle, Length: 148654, dtype: object

In [100]:
pd.set_option("display.max_columns",20)
df.head(2)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.0,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN

In [142]:
coun =0
for i in df["JobTitle"].str.split():
    for j in i:
        if j.lower() == "chief":
            coun =coun +1
coun

477

In [148]:
sum(df["JobTitle"].str.lower().str.contains(r"\bchief\b"))

627

In [160]:
df["JobTitle"].str.split().explode().str.lower()=="Chief"

0         False
0         False
0         False
0         False
1         False
          ...
148652    False
148653    False
148653    False
148653    False
148653    False
Name: JobTitle, Length: 380458, dtype: bool